sudo: false
language: node_js
node_js:
  - '0.12'
branches:
  only:
    - master
before_install:
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xjf phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - mv phantomjs "$TRAVIS_BUILD_DIR/tmp/phantomjs2"
  - export PHANTOMJS_BIN="$TRAVIS_BUILD_DIR/tmp/phantomjs2"
script:
  - npm run lint
  - npm run test-ci
  - npm run test-tz
  - npm run test-tz-extended
cache:
  directories:
    - node_modules
